#!/usr/bin/env tsx

/**
 * Update Model Configuration Script
 * 
 * This script uses the discovery and curation systems to automatically update
 * our model configuration files with only the flagship models we want to show.
 * 
 * Usage:
 * npm run update-models          # Update with curated flagship models
 * npm run update-models --dry    # Preview changes without updating files
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { modelDiscovery } from '../lib/models/discovery.js';
import { modelCurator } from '../lib/models/curation.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
const envPath = path.join(__dirname, '../.env.local');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach(line => {
    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0 && !key.startsWith('#')) {
      process.env[key.trim()] = valueParts.join('=').trim();
    }
  });
}

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes('--dry');
  const flagshipOnly = args.includes('--flagship');

  console.log('🎯 Updating model configuration with curated flagship models...\n');

  try {
    // Step 1: Discover all models
    console.log('🔍 Discovering models from all providers...');
    modelDiscovery.clearCache();
    const discoveryResults = await modelDiscovery.discoverAllModels();
    
    const allDiscoveredModels = discoveryResults.flatMap(result => 
      result.error ? [] : result.models
    );
    
    console.log(`📊 Discovered ${allDiscoveredModels.length} models from ${discoveryResults.length} providers`);

    // Step 2: Curate models
    console.log('\n🎨 Curating models...');
    const curatedModels = flagshipOnly 
      ? modelCurator.getFlagshipModels(allDiscoveredModels)
      : modelCurator.curateModels(allDiscoveredModels);
    
    console.log(`✨ Curated to ${curatedModels.length} flagship models:`);
    curatedModels.forEach(model => {
      const tier = model.tier === 'flagship' ? '🏆' : model.tier === 'premium' ? '⭐' : '📋';
      const verified = model.verified ? '✅' : '❌';
      console.log(`  ${tier} ${verified} ${model.id} (${model.provider}) - ${model.category}`);
    });

    // Step 3: Generate new configuration
    console.log('\n📝 Generating new configuration...');
    const newConfig = generateModelConfig(curatedModels);
    
    if (isDryRun) {
      console.log('\n🔍 DRY RUN - Configuration Preview:\n');
      console.log(newConfig);
      console.log('\n💡 To actually update files, run: npm run update-models');
      return;
    }

    // Step 4: Update config.ts
    const configPath = path.join(__dirname, '../lib/models/config.ts');
    console.log(`\n💾 Updating ${configPath}...`);
    
    // Read current config to preserve structure
    const currentConfig = fs.readFileSync(configPath, 'utf8');
    const updatedConfig = updateConfigFile(currentConfig, curatedModels);
    
    fs.writeFileSync(configPath, updatedConfig);
    console.log('✅ Updated lib/models/config.ts');

    // Step 5: Update pricing.ts if needed
    console.log('\n💰 Checking pricing configuration...');
    await updatePricingFile(curatedModels);

    console.log('\n🎉 Model configuration updated successfully!');
    console.log('\nNext steps:');
    console.log('1. Review the updated configuration files');
    console.log('2. Test the updated models work correctly');
    console.log('3. Commit and deploy changes');
    console.log('4. Run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_Cg4uBe79Ad0WMENHEQuPNFXJ36De/eSnGWYEPAQ"');

  } catch (error) {
    console.error('❌ Update failed:', error);
    process.exit(1);
  }
}

function generateModelConfig(curatedModels: any[]): string {
  const configLines: string[] = [
    '/**',
    ' * AI Model Configuration',
    ' * Generated by update-curated-models.ts',
    ' * Last updated: ' + new Date().toISOString(),
    ' */',
    '',
    'export interface Model {',
    '  id: string;',
    '  name: string;',
    '  provider: string;',
    '  maxTokens: number;',
    '  tier: "flagship" | "premium" | "standard" | "budget";',
    '  category: "reasoning" | "creative" | "general" | "fast" | "research";',
    '  isRecommended: boolean;',
    '}',
    '',
    'export const MODELS: Record<string, Model> = {'
  ];

  curatedModels.forEach(model => {
    configLines.push(`  '${model.id}': {`);
    configLines.push(`    id: '${model.id}',`);
    configLines.push(`    name: '${model.displayName}',`);
    configLines.push(`    provider: '${model.provider}',`);
    configLines.push(`    maxTokens: ${model.contextTokens || 128000},`);
    configLines.push(`    tier: '${model.tier}',`);
    configLines.push(`    category: '${model.category}',`);
    configLines.push(`    isRecommended: ${model.isRecommended}`);
    configLines.push('  },');
  });

  configLines.push('};');
  configLines.push('');
  configLines.push('// Export just the model IDs for backward compatibility');
  configLines.push('export const MODEL_CONTEXT_LIMITS = {');
  
  curatedModels.forEach(model => {
    configLines.push(`  '${model.id}': ${model.contextTokens || 128000},`);
  });
  
  configLines.push('};');

  return configLines.join('\n');
}

function updateConfigFile(currentConfig: string, curatedModels: any[]): string {
  // Extract the existing structure and update with curated models
  const lines = currentConfig.split('\n');
  const updatedLines: string[] = [];
  
  let inModelSection = false;
  let inContextSection = false;
  
  for (const line of lines) {
    if (line.includes('export const MODELS') || line.includes('MODEL_CONTEXT_LIMITS')) {
      // We'll replace these sections entirely
      if (line.includes('MODELS')) {
        inModelSection = true;
        updatedLines.push('export const MODELS = {');
        
        // Add curated models
        curatedModels.forEach(model => {
          updatedLines.push(`  '${model.id}': {`);
          updatedLines.push(`    id: '${model.id}',`);
          updatedLines.push(`    name: '${model.displayName}',`);
          updatedLines.push(`    provider: '${model.provider}',`);
          updatedLines.push(`    maxTokens: ${model.contextTokens || 128000},`);
          updatedLines.push(`    tier: '${model.tier}',`);
          updatedLines.push(`    category: '${model.category}',`);
          updatedLines.push(`    isRecommended: ${model.isRecommended}`);
          updatedLines.push('  },');
        });
        
      } else if (line.includes('MODEL_CONTEXT_LIMITS')) {
        inContextSection = true;
        updatedLines.push('export const MODEL_CONTEXT_LIMITS = {');
        
        // Add context limits
        curatedModels.forEach(model => {
          updatedLines.push(`  '${model.id}': ${model.contextTokens || 128000},`);
        });
      }
      continue;
    }
    
    if (line.includes('};') && (inModelSection || inContextSection)) {
      updatedLines.push('};');
      inModelSection = false;
      inContextSection = false;
      continue;
    }
    
    if (!inModelSection && !inContextSection) {
      updatedLines.push(line);
    }
  }
  
  return updatedLines.join('\n');
}

async function updatePricingFile(curatedModels: any[]) {
  const pricingPath = path.join(__dirname, '../lib/models/pricing.ts');
  
  if (!fs.existsSync(pricingPath)) {
    console.log('⚠️ Pricing file not found, skipping pricing updates');
    return;
  }

  try {
    const pricingContent = fs.readFileSync(pricingPath, 'utf8');
    
    // Check which models are missing pricing
    const missingPricing: string[] = [];
    
    curatedModels.forEach(model => {
      if (!pricingContent.includes(`'${model.id}'`)) {
        missingPricing.push(model.id);
      }
    });
    
    if (missingPricing.length > 0) {
      console.log('⚠️ Models missing pricing configuration:');
      missingPricing.forEach(id => console.log(`   • ${id}`));
      console.log('Please add pricing information for these models manually.');
    } else {
      console.log('✅ All curated models have pricing configuration');
    }
    
  } catch (error) {
    console.warn('Could not check pricing file:', error);
  }
}

// Add this script to package.json
function updatePackageJson() {
  const packagePath = path.join(__dirname, '../package.json');
  const packageContent = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
  
  if (!packageContent.scripts['update-models']) {
    packageContent.scripts['update-models'] = 'tsx scripts/update-curated-models.ts';
    fs.writeFileSync(packagePath, JSON.stringify(packageContent, null, 2));
    console.log('✅ Added update-models script to package.json');
  }
}

// Run the script
main().catch(console.error);